# Site settings
title: Sheng-Da Lyu's CV
description: Sheng-Da Lyu's CV
favicon: /resume/assets/img/avatar.JPG
baseurl: /resume
url: https://www.lvh.me/

# Build settings
markdown: kramdown

# Author settings
author:
  name: Sheng-Da Lyu
  title: Web Developer
  address: Taipei, Taiwan
  email: dragon90321@gmail.com
  github: sdlyu
  gavatar: /resume/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: 磊德資訊
      location: Taipei, Taiwawn
      title: Front-End/HTML5 Game Developer | HTML5 部門課長
      techused: React/Redux | Cocos Creator | FRP/RxJS | .net SignalR
      started: 2016
      duration: (2016/5 - Present)
      description:
        使用 React/Redux 建置未來事件交易前端<br>
        使用 SignalR 做即時資料傳輸互動<br>
        使用 Karma + Enzyme 做 React/Redux 單元測試及集成測試，並保持 80% 的測試覆蓋率<br>
        使用 Cocos Creator 建置 HTML5 遊戲頁面<br>
        實現眯牌動作及效果<br>
        帶領團隊使用 Cocos Creator 從零到能完整開發功能<br>
        提交並驗證 issue 給 Cocos Creator 團隊
    - work2:
      company: 上恩資訊-媽咪愛
      link: https://www.mamilove.com.tw
      location: Taipei, Taiwawn
      title: Web Developer | 資深網頁工程師
      techused: PHP Yii Larvel MySQL PostgreSQL Memcache DynamoDB Codeception | SASS/SCSS Bootstrap jQuery Backbone Gulp Webpack | Docker Compose/Machine/Swarm Vagrant
      started: 2015
      duration: (2015/1 - 2016/5)
      description:
        建置 UPN 官方網站<br>
        建置 ERP 及倉儲管理系統<br>
        使用 AWS service(EC2/RDS/SQS/ElasticSearch) 建置媽咪愛網站<br>
        RESTful API 設計<br>
        使用 Optimizly (A/B Test) 量化成果<br>
        優化頁面載入速度(降低 50% 載入時間)<br>
        支援多語系及多幣別<br>
        建置團隊 Docker 開發及測試環境
    - work3:
      company: Clotho 可蘿國際
      link: http://clotho.com.tw
      location: Taipei, Taiwan
      title: Front-end Developer
      techused: Shopify | JavaScript SASS/SCSS
      started: 2014
      duration: (2014/9 - 2015/3)
      description:
        提供網頁系統咨詢<br>
        網站前端改版並上線<br>
        7-11 物流串接<br>
    - work4:
      company: Ifalo 艾法諾科技
      location: Taichung, Taiwan
      title: Web Developer | 網頁工程師
      techused: PHP Zendframework MySQL Memcache Redis MongoDB | jQuery | Scala Spark
      started: 2013
      duration: (2013/12 - 2014/12)
      description:
        建置線上影音觀看平台<br>
        建置彩球即時下注系統<br>
        重構會員及報表系統<br>
        導入並建置 Spark 大數據分析系統<br>
  educationHistory:
    - education1:
      organization: 國立臺北大學
      degree: 研究所
      major: 資訊工程學系
      started: 2010
      duration: (2010 - 2012)
      description:
        研究方向－綠能、無線網路、感知網路、4G、IoT<br>
        教育部教材 Green Cellular Networks 編撰<br>
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Backend
      categories:
        - category1:
          name: PHP/Laravel/Yii2
          percentage: 80%
        - category2:
          name: Node.js/Express
          percentage: 60%
        - category3:
          name: SQL/MySQL/MariaDB
          percentage: 60%
        - category3:
          name: NoSQL/DynamoDB/MongoDB/Redis/Memcache
          percentage: 50%
        - category4:
          name: Python/Crawler
          percentage: 30%
    - skill2:
      name: Frontend
      categories:
        - category1:
          name: Cocos Creator/HTML5
          percentage: 80%
        - category2:
          name: jQuery/BootStrap
          percentage: 80%
        - category3:
          name: ReactJS/Redux
          percentage: 70%
        - category4:
          name: SASS/SCSS
          percentage: 70%
        - category5:
          name: Build Tool/Gulp/Webpack
          percentage: 60%
    - skill3:
      name: Operation
      categories:
        - category1:
          name: AWS/EC2/S3/RDS/SQS
          percentage: 60%
        - category2:
          name: Docker/Compose/Machine/Swarm
          percentage: 50%
    - skill4:
      name: App
      categories:
        - category1:
          name: React Native
          percentage: 50%
